spring:
  application:
    name: notification_service

  doc:
    api-docs:
      path: /api-docs
      enabled: true
    swagger-ui:
      path: /swagger-ui.html
      enabled: true

  activemq:
    broker-url: tcp://localhost:61616
    user: ${ACTIVEMQ_USER}
    password: ${ACTIVEMQ_PASSWORD}
    pool:
      enabled: false

  jms:
    template:
      default-destination: notification.queue
    listener:
      receive-timeout: 5000
    activemq:
      packages:
        trust-all: true
  listener:
    retry:
      max-attempts: 3
      interval: 5000

  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    queue: notification.queue
    exchange: myExchange
    routingKey: demo
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 2s
          max-attempts: 5
          multiplier: 1.5

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.transport.protocol: smtp
      mail.debug: true

server:
  port: 2024

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true