spring:
  application:
    name: order-management-system

  datasource:
    url: jdbc:mysql://localhost:3306/orders?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  doc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html

server:
  port: 2025

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/