spring:
  application:
    name: ConfigServer

  cloud:
    config:
      server:
        git:
          uri: https://github.com/sahithinasari/config-repo.git
          default-label: main
          clone-on-start: true

server:
  port: 2026

management:
  endpoints:
    web:
      exposure:
        include: health,info,env